export default {
    defaultSeverity: 'warning',
    plugins: ['stylelint-scss', '@stylistic/stylelint-plugin', 'stylelint-order'],
    // extends: ['stylelint-config-standard'],
    overrides: [
        {
            files: ['**/*.scss'],
            customSyntax: 'postcss-scss'
        }
    ],
    rules: {
        'alpha-value-notation': 'number',
        'annotation-no-unknown': [true, { ignoreAnnotations: ['default'] }],
        'at-rule-empty-line-before': ['always', {
            except: ['blockless-after-same-name-blockless', 'blockless-after-blockless', 'first-nested'],
            ignore: ['after-comment', 'first-nested', 'blockless-after-same-name-blockless', 'blockless-after-blockless'],
            ignoreAtRules: ['include', 'if', 'else']
        }],
        'at-rule-prelude-no-invalid': [true, { severity: 'error' }],
        'at-rule-no-vendor-prefix': true,
        'block-no-empty': true,
        'color-function-notation': 'legacy',
        'color-hex-length': 'short',
        'color-no-invalid-hex': [true, { severity: 'error' }],
        'comment-empty-line-before': null,
        'comment-no-empty': true,
        'comment-whitespace-inside': null,
        'custom-property-no-missing-var-function': [true, { severity: 'error' }],
        'custom-property-empty-line-before': ['always', {
            except: ['after-custom-property', 'first-nested'],
            ignore: ['after-comment', 'inside-single-line-block']
        }],
        'declaration-block-single-line-max-declarations': 2,
        'declaration-block-no-duplicate-custom-properties': [true, { severity: 'error' }],
        'declaration-block-no-duplicate-properties': [true, { ignore: ['consecutive-duplicates-with-different-values'] }],
        'declaration-empty-line-before': ['always', {
            except: [
                'after-comment',
                'after-declaration',
                'first-nested'
            ],
            ignore: [
                'after-comment',
                'inside-single-line-block'
            ]
        }],
        'declaration-block-no-redundant-longhand-properties': [true, { ignoreShorthands: ['inset', 'place-content'] }],
        'declaration-block-no-shorthand-property-overrides': true,
        'font-family-no-duplicate-names': [true, { severity: 'error' }],
        'font-family-no-missing-generic-family-keyword': true,
        'function-calc-no-unspaced-operator': true,
        'function-linear-gradient-no-nonstandard-direction': [true, { severity: 'error' }],
        'function-name-case': 'lower',
        'function-url-quotes': 'always',
        'function-url-no-scheme-relative': true,
        'hue-degree-notation': 'angle',
        'import-notation': 'string',
        'keyframe-block-no-duplicate-selectors': [true, { severity: 'error' }],
        'keyframe-declaration-no-important': true,
        'keyframe-selector-notation': 'percentage',
        'length-zero-no-unit': true,
        'lightness-notation': 'percentage',
        'max-nesting-depth': [5, { ignoreAtRules: ['each', 'media', 'supports', 'include'] }],
        'media-query-no-invalid': [true, { severity: 'error' }],
        'media-feature-name-no-vendor-prefix': [true, { severity: 'error' }],
        'media-feature-name-no-unknown': [true, { severity: 'error' }],
        'media-feature-range-notation': null,
        'named-grid-areas-no-invalid': [true, { severity: 'error' }],
        'no-descending-specificity': null,
        'no-duplicate-at-import-rules': [true, { severity: 'error' }],
        'no-duplicate-selectors': [true, { severity: 'error' }],
        'no-empty-source': true,
        'no-irregular-whitespace': [true, { severity: 'error' }],
        'no-invalid-double-slash-comments': [true, { severity: 'error' }],
        'no-invalid-position-at-import-rule': [true, { severity: 'error' }],
        'no-unknown-animations': [true, { severity: 'error' }],
        'no-unknown-custom-media': true,
        'no-unknown-custom-properties': null,
        'number-max-precision': 3,
        'property-no-unknown': [true, { severity: 'error' }],
        'property-no-vendor-prefix': true,
        'rule-empty-line-before': ['always-multi-line', {
            except: ['first-nested'],
            ignore: ['after-comment', 'first-nested']
        }],
        'shorthand-property-no-redundant-values': true,
        'selector-attribute-quotes': 'never',
        'selector-max-attribute': 3,
        'selector-max-combinators': 4,
        'selector-max-compound-selectors': 5,
        'selector-max-id': 1,
        'selector-max-pseudo-class': 3,
        'selector-no-qualifying-type': [true, { ignore: ['attribute', 'class', 'id'] }],
        'selector-no-vendor-prefix': true,
        'selector-not-notation': 'simple',
        'selector-pseudo-element-colon-notation': 'double',
        'selector-pseudo-class-no-unknown': [true, { severity: 'error' }],
        'selector-pseudo-element-no-unknown': [true, { ignorePseudoElements: ['range-track', 'range-thumb'] }],
        'selector-type-case': ['lower', { severity: 'error' }],
        'selector-type-no-unknown': [true, { ignore: ['custom-elements'], ignoreNamespaces: ['*', 'svg'] }],
        'selector-class-pattern': ['^[a-z0-9\\-]+$', { message: 'Selector should be written in lowercase with hyphens (selector-class-pattern)' }],
        'string-no-newline': [true, { severity: 'error' }],
        'unit-no-unknown': [true, { severity: 'error' }],
        'unit-disallowed-list': [['px']],
        'value-no-vendor-prefix': [true, { ignoreValues: [] }],
        'value-keyword-case': 'lower',

        '@stylistic/at-rule-name-case': 'lower',
        '@stylistic/at-rule-name-newline-after': null,
        '@stylistic/at-rule-name-space-after': 'always',
        '@stylistic/at-rule-semicolon-newline-after': null,
        '@stylistic/at-rule-semicolon-space-before': 'never',
        '@stylistic/block-closing-brace-empty-line-before': 'never',
        '@stylistic/block-closing-brace-newline-after': ['always', { ignoreAtRules: ['if', 'else'] }],
        '@stylistic/block-closing-brace-newline-before': 'always-multi-line',
        '@stylistic/block-closing-brace-space-after': null,
        '@stylistic/block-closing-brace-space-before': 'always-single-line',
        '@stylistic/block-opening-brace-newline-after': 'always-multi-line',
        '@stylistic/block-opening-brace-newline-before': null,
        '@stylistic/block-opening-brace-space-after': 'always-single-line',
        '@stylistic/block-opening-brace-space-before': 'always-single-line',
        // "@stylistic/color-hex-case": "upper",
        '@stylistic/declaration-bang-space-after': 'never',
        '@stylistic/declaration-bang-space-before': 'always',
        '@stylistic/declaration-block-semicolon-newline-after': 'always-multi-line',
        '@stylistic/declaration-block-semicolon-newline-before': 'never-multi-line',
        '@stylistic/declaration-block-semicolon-space-after': 'always-single-line',
        '@stylistic/declaration-block-semicolon-space-before': 'never',
        '@stylistic/declaration-block-trailing-semicolon': ['always', { severity: 'error' }],
        '@stylistic/declaration-colon-newline-after': 'always-multi-line',
        '@stylistic/declaration-colon-space-after': 'always-single-line',
        '@stylistic/declaration-colon-space-before': 'never',
        '@stylistic/function-comma-newline-after': 'always-multi-line',
        '@stylistic/function-comma-newline-before': null,
        '@stylistic/function-comma-space-after': 'always-single-line',
        '@stylistic/function-comma-space-before': 'never',
        '@stylistic/function-max-empty-lines': 0,
        '@stylistic/function-parentheses-newline-inside': 'always-multi-line',
        '@stylistic/function-parentheses-space-inside': 'never-single-line',
        '@stylistic/function-whitespace-after': 'always',
        '@stylistic/indentation': 4,
        '@stylistic/linebreaks': 'unix',
        '@stylistic/max-empty-lines': 1,
        '@stylistic/max-line-length': 140,
        '@stylistic/media-feature-colon-space-after': 'always',
        '@stylistic/media-feature-colon-space-before': 'never',
        '@stylistic/media-feature-name-case': 'lower',
        '@stylistic/media-feature-parentheses-space-inside': 'never',
        '@stylistic/media-feature-range-operator-space-after': 'always',
        '@stylistic/media-feature-range-operator-space-before': 'always',
        '@stylistic/media-query-list-comma-newline-after': 'always-multi-line',
        '@stylistic/media-query-list-comma-space-after': 'always-single-line',
        '@stylistic/media-query-list-comma-space-before': 'never',
        '@stylistic/no-eol-whitespace': true,
        '@stylistic/no-empty-first-line': true,
        '@stylistic/no-extra-semicolons': [true, { severity: 'error' }],
        '@stylistic/no-missing-end-of-source-newline': true,
        '@stylistic/number-no-trailing-zeros': true,
        '@stylistic/number-leading-zero': 'always',
        '@stylistic/property-case': 'lower',
        '@stylistic/selector-attribute-brackets-space-inside': 'never',
        '@stylistic/selector-attribute-operator-space-after': 'never',
        '@stylistic/selector-attribute-operator-space-before': 'never',
        '@stylistic/selector-combinator-space-after': 'always',
        '@stylistic/selector-combinator-space-before': 'always',
        '@stylistic/selector-descendant-combinator-no-non-space': [true, { severity: 'error' }],
        '@stylistic/selector-list-comma-newline-after': 'always-multi-line',
        '@stylistic/selector-list-comma-space-before': 'never',
        '@stylistic/selector-pseudo-class-case': 'lower',
        '@stylistic/selector-pseudo-class-parentheses-space-inside': 'never',
        '@stylistic/selector-pseudo-element-case': 'lower',
        '@stylistic/selector-max-empty-lines': 1,
        '@stylistic/string-quotes': 'single',
        '@stylistic/unicode-bom': 'never',
        '@stylistic/unit-case': 'lower',
        '@stylistic/value-list-comma-newline-after': 'always-multi-line',
        '@stylistic/value-list-comma-space-after': 'always-single-line',
        '@stylistic/value-list-comma-space-before': 'never',
        '@stylistic/value-list-max-empty-lines': 0,

        'scss/at-else-closing-brace-newline-after': 'always-last-in-chain',
        'scss/at-else-closing-brace-space-after': 'always-intermediate',
        'scss/at-else-empty-line-before': 'never',
        'scss/at-if-closing-brace-newline-after': 'always-last-in-chain',
        'scss/at-if-closing-brace-space-after': 'always-intermediate',
        'scss/at-extend-no-missing-placeholder': true,
        'scss/at-function-pattern': '^[a-z]+([a-z0-9-]+[a-z0-9]+)?$',
        'scss/at-import-partial-extension-disallowed-list': ['scss'],
        'scss/at-mixin-pattern': '^[a-z]+([a-z0-9-]+[a-z0-9]+)?$',
        'scss/at-mixin-argumentless-call-parentheses': 'never',
        'scss/at-mixin-parentheses-space-before': 'never',
        'scss/at-rule-no-unknown': true,
        'scss/dollar-variable-colon-space-after': 'always',
        'scss/dollar-variable-colon-space-before': 'never',
        'scss/dollar-variable-pattern': '^[_]?[a-z]+([a-z0-9-]+[a-z0-9]+)?$',
        'scss/dollar-variable-no-missing-interpolation': true,
        'scss/declaration-nested-properties-no-divided-groups': true,
        'scss/operator-no-newline-after': true,
        'scss/operator-no-newline-before': true,
        'scss/operator-no-unspaced': true,
        'scss/percent-placeholder-pattern': '^[a-z]+([a-z0-9-]+[a-z0-9]+)?$',
        'scss/selector-no-redundant-nesting-selector': true,
        'scss/no-duplicate-dollar-variables': true,

        'order/order': [
            {
                type: 'at-rule',
                name: 'use'
            },
            {
                type: 'at-rule',
                name: 'extend'
            },
            {
                type: 'at-rule',
                name: 'include'
            },

            {
                type: 'at-rule',
                name: 'include',
                parameter: 'transform'
            },

            'dollar-variables',
            'custom-properties',
            'declarations',

            {
                type: 'at-rule',
                name: 'include',
                parameter: 'focusable'
            },

            {
                type: 'at-rule',
                name: 'include',
                parameter: 'respond'
            },

            {
                type: 'at-rule',
                name: 'include',
                parameter: 'print'
            },

            {
                type: 'at-rule',
                name: 'include',
                parameter: 'nomotion'
            },

            'rules'
        ],
        'order/properties-order': [
            'content',
            'position',
            'display',

            'grid-template-columns',
            'grid-template-rows',
            'grid-column',
            'grid-row',
            'grid-area',
            'grid-template-areas',

            'flex-direction',
            'flex-flow',
            'flex-wrap',
            'flex-grow',
            'flex-shrink',
            'flex-basis',
            'order',
            'justify-content',
            'align-items',
            'align-content',
            'align-self',
            'gap',

            'z-index',
            'float',
            'clear',
            'overflow',
            'visibility',
            'box-sizing',
            'box-decoration-break',
            'vertical-align',
            'object-fit',

            'resize',
            'outline-offset',

            'width',
            'height',
            'min-width',
            'min-height',
            'max-width',
            'max-height',

            'column-count',
            'column-gap',
            'column-rule-style',
            'column-rule-width',
            'column-rule-color',
            'column-rule',
            'column-span',
            'column-width',

            'top',
            'right',
            'bottom',
            'left',

            'margin',
            'margin-top',
            'margin-bottom',
            'margin-left',
            'margin-right',

            'margin-block',
            'margin-block-start',
            'margin-block-end',
            'margin-inline-start',
            'margin-inline-end',

            'padding',
            'padding-top',
            'padding-bottom',
            'padding-left',
            'padding-right',

            'padding-block',
            'padding-block-start',
            'padding-block-end',
            'padding-inline-start',
            'padding-inline-end',

            'border',
            'border-color',
            'border-width',
            'border-style',
            'border-top',
            'border-bottom',
            'border-left',
            'border-right',
            'border-top-color',
            'border-bottom-color',
            'border-left-color',
            'border-right-color',
            'border-top-width',
            'border-bottom-width',
            'border-left-width',
            'border-right-width',
            'border-top-style',
            'border-bottom-style',
            'border-left-style',
            'border-right-style',

            'border-radius',
            'border-top-left-radius',
            'border-top-right-radius',
            'border-bottom-right-radius',
            'border-bottom-left-radius',

            'border-image',
            'border-image-source',
            'border-image-slice',
            'border-image-width',
            'border-image-outset',
            'border-image-repeat',

            'table-layout',
            'border-collapse',
            'caption-side',
            'empty-cells',

            'outline',
            'outline-style',
            'outline-color',
            'outline-width',
            'outline-offset',

            'background',
            'background-color',
            'background-image',
            'background-repeat',
            'background-attachment',
            'background-position',
            'background-size',
            'background-origin',
            'background-clip',
            'background-blend-mode',

            'font',
            'font-family',
            'font-size',
            'font-style',
            'font-weight',
            'font-variant',

            'color',
            'direction',
            'unicode-bidi',
            'line-height',
            'text-align',
            'text-align-last',
            'text-justify',
            'text-decoration',
            'text-decoration-color',
            'text-decoration-line',
            'text-decoration-style',
            'text-decoration-skip',
            'text-transform',
            'text-indent',
            'letter-spacing',
            'word-spacing',
            'white-space',
            'word-wrap',
            'word-break',
            'text-overflow',
            'hanging-punctuation',
            'quotes',
            'tab-size',
            'user-select',

            'text-shadow',
            'box-shadow',

            'caret-color',

            'list-style',
            'list-style-type',
            'list-style-position',
            'list-style-image',

            'counter-increment',
            'counter-reset',

            'opacity',
            'filter',
            'cursor',

            'transform',
            'transform-origin',
            'transform-style',
            'perspective',
            'perspective-origin',
            'backface-visibility',

            'transition',
            'transition-property',
            'transition-duration',
            'transition-delay',
            'transition-timing-function',

            'animation',
            'animation-name',
            'animation-duration',
            'animation-timing-function',
            'animation-delay',
            'animation-iteration-count',
            'animation-direction',
            'animation-fill-mode',
            'animation-play-state',
            '@keyframes'
        ]
    }
};
